categories:
  - title: Features
    labels:
      - feature
      - enhancement
  - title: Changes
    labels:
      - refactor
      - chore
  - title: Bug Fixes
    labels:
      - fix
      - bug
  - title: Tests
    labels:
      - test
  - title: BREAKING CHANGES
    labels:
      - BREAKING CHANGE
change-template: '- $TITLE #$NUMBER (@$AUTHOR)'
template: |
  $CHANGES
