version: "3.7"

volumes:
  postgres-storage:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/.data/postgres"
      o: bind

services:
  database:
    container_name: accesso-database
    image: postgres:11.5
    restart: always
    volumes:
      - "postgres-storage:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: accesso
      POSTGRES_PASSWORD: accesso
      POSTGRES_DB: accesso
    expose:
      - "5432"
    ports:
      - "5432:5432"
