openapi: 3.0.1
info:
  title: Authmenow API.
  version: 0.1.0
servers:
  - url: /api/v0
paths:
  "/session":
    get:
      tags: [authorization]
      description: Get info about current session
      summary: Get session
      operationId: sessionGet
      responses:
        200:
          $ref: "#/components/responses/UserAuthenticated"
        401:
          $ref: "#/components/responses/UserAnonymous"

    post:
      tags: [authorization]
      description: Create session
      summary: Login
      operationId: sessionCreate
      parameters:
        - $ref: "#/components/parameters/CsrfToken"
      requestBody:
        $ref: "#/components/requestBodies/Login"
      responses:
        200:
          description: Session successfully created
          headers:
            Set-Cookie:
              $ref: "#/components/headers/AuthCookie"

    delete:
      tags: [authorization]
      description: Delete session
      summary: Logout
      operationId: sessionDelete
      parameters:
        - $ref: "#/components/parameters/CsrfToken"
      security:
        - cookieAuth: []
      responses:
        200:
          description: Session successfully deleted
          headers:
            Set-Cookie:
              $ref: "#/components/headers/DeleteAuthCookie"

  "/oauth/request-authorization":
    post:
      tags: [OAuth]
      description: Request authorization code
      operationId: internalRequestOauth
      security:
        - cookieAuth: []
      parameters:
        - $ref: "#/components/parameters/CsrfToken"
      requestBody:
        $ref: "#/components/requestBodies/OauthAuth"
      responses:
        200:
          $ref: "#/components/responses/OauthSuccess"
        400:
          $ref: "#/components/responses/OauthFailure"
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: authmenowUser

  parameters:
    CsrfToken:
      name: csrfToken
      in: header
      required: true
      schema:
        type: string
        example: y7WVzQkcanN9KtApzwXjevQ5AHdpxp

  headers:
    AuthCookie:
      schema:
        type: string
        example: authmenowUser=hDxrvkba5yx3eAMDr5; Path=/; HttpOnly; Secure

    DeleteAuthCookie:
      schema:
        type: string
        example: "authmenowUser="

    SetCsrfToken:
      schema:
        type: string
        example: csrfToken=y7WVzQkcanN9KtApzwXjevQ5AHdpxp; Path=/

  requestBodies:
    OauthAuth:
      required: true
      content:
        application/json:
          schema:
            required:
              - responseType
              - clientId
              - redirectUri

              - login
              - password
            properties:
              responseType:
                type: string
                enum:
                  - code
                  # - token
              clientId:
                type: string
                format: uuid
              redirectUri:
                type: string
                format: uri
                example: appname://authorized/success
              state:
                type: string
                example: any_client_specific_data

              password:
                type: string
              login:
                description: email or username
                type: string

    Login:
      required: true
      content:
        application/json:
          schema:
            properties:
              login:
                type: string
                description: email or username
              password:
                type: string

  responses:
    UserAuthenticated:
      description: User authenticated in Authmenow
      headers:
        Set-Cookie:
          $ref: "#/components/headers/SetCsrfToken"
      content:
        application/json:
          schema:
            properties:
              username:
                type: string
                example: johndoe
              displayName:
                type: string
                example: John Doe
    UserAnonymous:
      description: User not authenticated yet in Authmenow
      headers:
        Set-Cookie:
          $ref: "#/components/headers/SetCsrfToken"
    OauthSuccess:
      description: Authorization success
      content:
        application/json:
          schema:
            required:
              - authorizationCode
            properties:
              authorizationCode:
                type: string
                example: U5Y5B8rBjbByp9GyasGYEpK9jEKB7FUNNAZxrzxX8jFtkgbfHKBrq9fyTF
    OauthFailure:
      description: Failed authorization request. Should redirect to redirect_uri with that properties, only if redirect_uri is valid and client is valid.
      content:
        application/json:
          schema:
            required:
              - error
            properties:
              error:
                type: string
                enum:
                  - invalid_request
                  - unauthorized_client
                  - access_denied
                  - unsupported_response_type
                  # - invalid_scope
                  - server_error
                  - temporarily_unavailable
              errorDescription:
                type: string
              errorUri:
                type: string
                format: uri
              state:
                type: string
                example: any_client_specific_data
