[package]
authors = ["Sergey Sova <mail@sergeysova.com>"]
edition = "2018"
name = "accesso-core"
version = "0.3.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
chrono = { version = "0.4.19", default-features = false, features = ["std", "clock"] }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.8.2", features = ["v4"] }
validator = "0.13.0"
validator_derive = "0.13.0"

[dev-dependencies]
insta = "0.15.0"
mockall = "0.9.1"
