debug = true

[cookies]
http_only = false
secure = false

[database]
database = "accesso"
host = "localhost"
password = "accesso"
user = "accesso"
pool_size = 2

[sendgrid]
enabled = false

[server]
host = "localhost"
port = 9010
