[package]
authors = ["Sergey Sova <mail@sergeysova.com>"]
edition = "2018"
name = "accesso-api-admin"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
actix-rt = "1.0.0"
actix-swagger = "0.1.1"
actix-web = "2.0.0"
diesel = {version = "1.4.3", features = ["r2d2", "postgres"]}
dotenv = "0.15.0"
env_logger = "0.7.1"
futures = "0.3.1"
r2d2 = "0.8.8"
serde = {version = "1.0.104", features = ["derive"]}
uuid = {version = "0.8.1", features = ["serde", "v4"]}
