[package]
authors = ["Sergey Sova <mail@sergeysova.com>"]
edition = "2018"
name = "accesso-api-admin"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
accesso-settings = {"path" = "../settings"}
accesso-core = {"path" = "../core"}
accesso-db = {"path" = "../db"}
accesso-app = { "path" = "../app" }
actix-http = "3.0.0-beta.8"
actix-cors = "0.6.0-beta.2"
async-trait = "0.1.50"
derive_more = { version = "0.99.16", features = ["display"]}
awc = "3.0.0-beta.7"
tokio = "1.7.1"
actix-router = "0.4.0"
actix-rt = "2.2.0"
actix-swagger = "=0.3.0-beta.1"
actix-web = "4.0.0-beta.8"
chrono = "0.4.19"
dotenv = "0.15.0"
futures = "0.3.15"
r2d2 = "0.8.8"
serde = {version = "1.0.104", features = ["derive"]}
serde_json = "1.0.64"
serde_plain = "0.1.0"
uuid = { version = "0.8.2", features = ["v4", "serde"] }
tracing = "0.1.26"
tracing-subscriber = { version = "0.2.18", features = ["env-filter", "tracing-log"] }
thiserror = "1.0.26"
eyre = "0.6.5"
color-eyre = "0.5.11"
tracing-actix-web = "0.4.0-beta.9"
