name: API Docker Image CI

on:
  push:
    branches:
      - master
      - dev
    paths:
      - ".github/workflows/api-docker-image.yml"
      - "db/*"
      - "public-api/*"
      - "migrations/*"
      - "docker-entrypoint.sh"
      - "Dockerfile"
      - "Cargo.lock"

jobs:
  public-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.8
        with:
          name: authmenow/backend/public-api
          username: sergeysova
          password: ${{ secrets.GITHUB_TOKEN }}
          snapshot: true
          registry: docker.pkg.github.com
          buildargs: CRATE_NAME=public-api
