name: AWS Lambda DEV CI

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup ZIG
        uses: nektro/actions-setup-zig@v1

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Reuse cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: rustc-${{ steps.toolchain.outputs.rustc_hash }}-cargo-${{ hashFiles('./Cargo.toml') }}
          restore-keys: |
            rustc-${{ steps.toolchain.outputs.rustc_hash }}-cargo-${{ hashFiles('./Cargo.toml' }}
            rustc-${{ steps.toolchain.outputs.rustc_hash }}-cargo-
            rustc-

      - name: Install cargo-lambda
        uses: zerj9/setup-cargo-lambda@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build lambda function
        run: cargo lambda build --release --arm64 --package accesso-api-internal

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Deploy lambda function
        run: cargo lambda deploy --env-var DATABASE_URL=${{ secrets.DATABASE_URL }} --iam-role ${{ secrets.IAM_ROLE }} accesso-api-internal
