name: API Docker Image CI

on:
  pull_request:
    branches:
      - master
      - dev

  push:
    branches:
      - master
      - dev
    tags:
      - "api-admin@*"
      - "api-internal@*"
      - "api-private@*"
      - "api-public@*"

jobs:
  builder-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: none
          filters: |
            builder:
              - 'builder.Dockerfile'

      - name: Publish Docker
        if: steps.changes.outputs.builder == 'true'
        uses: sergeysova/docker-publish-action@master
        with:
          image: accesso-app/backend/builder
          registry: docker.pkg.github.com
          username: sergeysova
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: builder.Dockerfile
          tag_from_label: version
          tag_separator: "@"
          cache: true

  start-tools-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: none
          filters: |
            tools:
              - 'start-tools.Dockerfile'

      - name: Publish Docker
        if: steps.changes.outputs.tools == 'true'
        uses: sergeysova/docker-publish-action@master
        with:
          image: accesso-app/backend/start-tools
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: start-tools.Dockerfile
          tag_from_label: version
          tag_separator: "@"
          cache: true

  api-image:
    strategy:
      matrix:
        # api: [admin, internal, private, public]
        api: [admin, internal, public]

    name: api-${{ matrix.api }}
    needs: [builder-image, start-tools-image]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: none
          filters: |
            source:
              - 'api-${{ matrix.api }}/**'
              - 'core/**'
              - 'db/**'
              - 'app/**'
              - 'resources/**'
              - 'Cargo.lock'
              - 'Cargo.toml'
              - 'Dockerfile'

      - name: Publish Docker image
        if: steps.changes.outputs.source == 'true'
        uses: sergeysova/docker-publish-action@v1
        with:
          image: accesso-app/backend/api-${{ matrix.api }}
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          buildargs: API_NAME=${{ matrix.api }}
          snapshot: "true"
          tag_extra: latest
          tag_semver: skip
          tag_separator: "@"
          semver_higher: "true"

  deploy:
    name: Trigger deploy to DEV
    runs-on: ubuntu-latest
    needs: [api-image]
    steps:
      - name: Trigger deploy to Dev
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TRIGGER_DEPLOY_TOKEN }}
          repository: accesso-app/releases
          event-type: deploy-dev
