name: API Docker Image CI

on:
  pull_request:
    branches:
      - master
      - dev

  push:
    branches:
      - master
      - dev
    paths:
      - ".github/workflows/image-api.yml"
      - "db/**"
      - "core/**"
      - "migrations/**"
      - "api-admin/**"
      - "api-internal/**"
      - "api-private/**"
      - "api-public/**"
      - "docker-entrypoint.sh"
      - "Dockerfile"
      - "builder.Dockerfile"
      - "start-tools.Dockerfile"
      - "Cargo.lock"
    tags:
      - "api-admin@*"
      - "api-internal@*"
      - "api-private@*"
      - "api-public@*"

jobs:
  builder-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish Docker
        uses: sergeysova/docker-publish-action@master
        with:
          image: accesso-app/backend/builder
          registry: docker.pkg.github.com
          username: sergeysova
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: builder.Dockerfile
          tag_from_label: version
          tag_separator: "@"
          cache: true

  start-tools-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish Docker
        uses: sergeysova/docker-publish-action@master
        with:
          image: accesso-app/backend/start-tools
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: start-tools.Dockerfile
          tag_from_label: version
          tag_separator: "@"
          cache: true

  api-image:
    strategy:
      matrix:
        # api: [admin, internal, private, public]
        api: [internal, public]

    name: api-${{ matrix.api }}
    needs: [builder-image, start-tools-image]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish Docker
        uses: sergeysova/docker-publish-action@v1
        with:
          image: accesso-app/backend/api-${{ matrix.api }}
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          buildargs: API_NAME=${{ matrix.api }}
          snapshot: "true"
          tag_extra: latest
          tag_semver: skip
          tag_separator: "@"
          semver_higher: "true"

      - name: Trigger deploy to Dev
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TRIGGER_DEPLOY_TOKEN }}
          repository: accesso-app/releases
          event-type: deploy-dev
          client-payload: '{"github": ${{ toJson(github) }}}'
